### ISSUE TITLE
PhotonError on filtering relation items

### ISSUE THREAD

**Issue by 19majkel94** [prisma/photonjs#113]
I've played a bit with examples from `prisma2 init` and I have this query:

```ts
  const postsByUser = await photon.users.findOne({
    where: {
      email: "alice@prisma.io"
    },
    select: {
      name: true,
      email: true,
      posts: {
        // here I want only published posts
        where: {
          published: true
        },
        select: {
          title: true,
          // just for checking query response correctness
          published: true
        }
      }
    }
  });
```
but I received this runtime error:

```
PhotonError:
Invalid `photon.users.findOne()` invocation in /usr/app/src/script.ts:40:42

{
  where: {
    email: 'alice@prisma.io'
  },
  select: {
    name: true,
    email: true,
    posts: {
      where: {
        published: true
        ~~~~~~~~~
      },
      select: {
        title: true,
        published: true
      }
    }
  }
}

Unknown arg `published` in select.posts.where.published for type UserWhereInput. Available args:

type UserWhereInput {
  id?: String | StringFilter
  email?: String | StringFilter
  name?: String | NullableStringFilter | null
  posts?: PostFilter
  AND?: UserWhereInput
  OR?: UserWhereInput
  NOT?: UserWhereInput
}


    at Document.validate (/usr/app/node_modules/@generated/photon/runtime/index.js:6185:23)
    at UserClient.get document [as document] (/usr/app/node_modules/@generated/photon/index.js:161:22)
    at UserClient.then (/usr/app/node_modules/@generated/photon/index.js:183:61)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

@nikolasburk said that it looks like a bug for him 😉

**Comment by timsuchanek** [comment]
This is fixed in the latest version. Please let me know if you still face this issue.
