### ISSUE TITLE
Prisma2 fails if schema contains multiple rels between same types

### ISSUE THREAD

**Issue by victordombrovskiy** [prisma/photonjs#131]
My schema has two rels between User and Event: 
- userIsCreatorOfEvent
- userIsOrganiserOfEvent

To disambiguate this I use  @relation attribute. But it doesn't work:
```
model User {
  id                    String      @default(cuid()) @id @unique
  name             String
  createdEvents         Event[]     @relation(name: "userIsCreatorOfEvent")
  organisedEvents       Event[]     @relation(name: "userIsOrganiserOfEvent")
}

model Event {
  id                    String      @default(cuid()) @id @unique
  name                  String
  creator               User        @relation(name: "userIsCreatorOfEvent")
  organiser             User        @relation(name: "userIsOrganiserOfEvent")
}
```

It throws the following error:

`thread 'main' panicked at 'Did not find a relation for those for model Event and field organiser', src/libcore/option.rs:1034:5`

**Comment by victordombrovskiy** [comment]
Another example, related to the same issue, but with different error:

```
model Location {
  id                    ID
  latitude              Float
  longitude             Float
  postalCode            PostalCode? @relation(name: "LocationBelongsToPostalCode")
  centroidOf            PostalCode? @relation(name: "LocationIsCentroidOfPostalCode")
}

model PostalCode {
  id                    ID
  number                String
  locations             Location[]  @relation(name: "LocationBelongsToPostalCode")
  centroid              Location    @relation(name: "LocationIsCentroidOfPostalCode")
}
```

Error:

```
Error: Error in lift engine for rpc inferMigrationSteps:
  thread 'main' panicked at 'It's not allowed that both sides of a relation specify the inline policy. The field was centroid on model PostalCode. The related field was postalCode on model Location.', prisma-models/src/datamodel_converter.rs:202:37
```

**Comment by pantharshit00** [comment]
I can confirm this.

Related: https://github.com/prisma/lift/issues/50
