### ISSUE TITLE
Photon as Nestjs Service

### ISSUE THREAD

**Issue by marcjulian** [prisma/photonjs#154]
prisma2 version `prisma2@2.0.0-alpha.52, binary version: 4f33077038a490e4b2c1c260f109309e4a447181` on Mac.

My prisma schema is

```prisma
datasource db {
  provider = "sqlite"
  url      = "file:../db/dev.db"
}

generator photon {
  provider = "photonjs"
}

model User {
  id        String @default(cuid()) @id @unique
  email     String @unique
  password  String
  firstname String
  lastname  String
}
```

I am trying to use Photon as a Nestjs Service.

I tried using Photon like:

```typescript
import { Injectable } from '@nestjs/common';
import Photon from '@generated/photon';

@Injectable()
export class PhotonService {
  photon = new Photon();
  constructor() {}

  disconnect() {
    this.photon.disconnect();
  }
}
```

and like this:

```typescript
import { Injectable } from '@nestjs/common';
import Photon from '@generated/photon';

@Injectable()
export class PhotonService extends Photon {
  constructor() {
    super();
  }
}
```

I am using the `PhotonService` in a `UserService` to find a user by id or email:

```typescript
import { Injectable } from '@nestjs/common';
import { PhotonService } from './photon.service';
import { User } from '@generated/photon';

@Injectable()
export class UserService {
  constructor(private photonService: PhotonService) {}

  async findUserById(userId: string): Promise<User> {
    try {
      return this.photonService.users.findOne({
        where: { id: userId }
      });
    } finally {
      await this.photonService.disconnect();
    }
  }

  async findUserByEmail(email: string): Promise<User> {
    try {
      return this.photonService.users.findOne({
        where: { email: email }
      });
    } finally {
      await this.photonService.disconnect();
    }
  }
}
```

If I call the graphql endpoint of Nestjs which will lookup a user by email for login I receive the following exception:

```
{
  "errors": [
    {
      "message": "Error in Photon: \n{\n  \"name\": \"RequestError\",\n  \"code\": \"ECONNREFUSED\",\n  \"host\": \"localhost:65398\",\n  \"hostname\": \"localhost\",\n  \"method\": \"POST\",\n  \"path\": \"/\",\n  \"protocol\": \"http:\",\n  \"url\": \"http://localhost:65398/\",\n  \"gotOptions\": {\n    \"path\": \"/\",\n    \"protocol\": \"http:\",\n    \"slashes\": true,\n    \"auth\": null,\n    \"host\": \"localhost:65398\",\n    \"port\": \"65398\",\n    \"hostname\": \"localhost\",\n    \"hash\": null,\n    \"search\": null,\n    \"query\": null,\n    \"pathname\": \"/\",\n    \"href\": \"http://localhost:65398/\",\n    \"retry\": {\n      \"methods\": {},\n      \"statusCodes\": {},\n      \"errorCodes\": {}\n    },\n    \"headers\": {\n      \"user-agent\": \"got/9.6.0 (https://github.com/sindresorhus/got)\",\n      \"content-type\": \"application/json\",\n      \"accept\": \"application/json\",\n      \"accept-encoding\": \"gzip, deflate\",\n      \"content-length\": 187\n    },\n    \"hooks\": {\n      \"beforeRequest\": [],\n      \"beforeRedirect\": [],\n      \"beforeRetry\": [],\n      \"afterResponse\": [],\n      \"beforeError\": [],\n      \"init\": []\n    },\n    \"decompress\": true,\n    \"throwHttpErrors\": true,\n    \"followRedirect\": true,\n    \"stream\": false,\n    \"form\": false,\n    \"json\": true,\n    \"cache\": false,\n    \"useElectronNet\": false,\n    \"body\": \"{\\\"query\\\":\\\"query {\\\\n  findOneUser(where: {\\\\n    email: \\\\\\\"lisa@simpson.de\\\\\\\"\\\\n  }) {\\\\n    id\\\\n    email\\\\n    password\\\\n    firstname\\\\n    lastname\\\\n  }\\\\n}\\\",\\\"variables\\\":{},\\\"operationName\\\":\\\"\\\"}\",\n    \"method\": \"POST\",\n    \"forceRefresh\": true\n  }\n}",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "login"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: Error in Photon: ",
            "{",
            "  \"name\": \"RequestError\",",
            "  \"code\": \"ECONNREFUSED\",",
            "  \"host\": \"localhost:65398\",",
            "  \"hostname\": \"localhost\",",
            "  \"method\": \"POST\",",
            "  \"path\": \"/\",",
            "  \"protocol\": \"http:\",",
            "  \"url\": \"http://localhost:65398/\",",
            "  \"gotOptions\": {",
            "    \"path\": \"/\",",
            "    \"protocol\": \"http:\",",
            "    \"slashes\": true,",
            "    \"auth\": null,",
            "    \"host\": \"localhost:65398\",",
            "    \"port\": \"65398\",",
            "    \"hostname\": \"localhost\",",
            "    \"hash\": null,",
            "    \"search\": null,",
            "    \"query\": null,",
            "    \"pathname\": \"/\",",
            "    \"href\": \"http://localhost:65398/\",",
            "    \"retry\": {",
            "      \"methods\": {},",
            "      \"statusCodes\": {},",
            "      \"errorCodes\": {}",
            "    },",
            "    \"headers\": {",
            "      \"user-agent\": \"got/9.6.0 (https://github.com/sindresorhus/got)\",",
            "      \"content-type\": \"application/json\",",
            "      \"accept\": \"application/json\",",
            "      \"accept-encoding\": \"gzip, deflate\",",
            "      \"content-length\": 187",
            "    },",
            "    \"hooks\": {",
            "      \"beforeRequest\": [],",
            "      \"beforeRedirect\": [],",
            "      \"beforeRetry\": [],",
            "      \"afterResponse\": [],",
            "      \"beforeError\": [],",
            "      \"init\": []",
            "    },",
            "    \"decompress\": true,",
            "    \"throwHttpErrors\": true,",
            "    \"followRedirect\": true,",
            "    \"stream\": false,",
            "    \"form\": false,",
            "    \"json\": true,",
            "    \"cache\": false,",
            "    \"useElectronNet\": false,",
            "    \"body\": \"{\\\"query\\\":\\\"query {\\\\n  findOneUser(where: {\\\\n    email: \\\\\\\"lisa@simpson.de\\\\\\\"\\\\n  }) {\\\\n    id\\\\n    email\\\\n    password\\\\n    firstname\\\\n    lastname\\\\n  }\\\\n}\\\",\\\"variables\\\":{},\\\"operationName\\\":\\\"\\\"}\",",
            "    \"method\": \"POST\",",
            "    \"forceRefresh\": true",
            "  }",
            "}",
            "    at PhotonFetcher.<anonymous> (/Users/mj/Dev/wip/node_modules/@generated/photon/index.js:34:23)",
            "    at Generator.throw (<anonymous>)",
            "    at rejected (/Users/mj/Dev/wip/node_modules/@generated/photon/index.js:5:65)",
            "    at process._tickCallback (internal/process/next_tick.js:68:7)"
          ]
        }
      }
    }
  ],
  "data": null
}
```

And also for the next api call I receive another error:

```
{
  "errors": [
    {
      "message": "Error in Photon: \nEngine has already been stopped",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "login"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: Error in Photon: ",
            "Engine has already been stopped",
            "    at PhotonFetcher.<anonymous> (/Users/mj/Dev/wip/node_modules/@generated/photon/index.js:34:23)",
            "    at Generator.throw (<anonymous>)",
            "    at rejected (/Users/mj/Dev/wip/node_modules/@generated/photon/index.js:5:65)",
            "    at process._tickCallback (internal/process/next_tick.js:68:7)"
          ]
        }
      }
    }
  ],
  "data": null
}
```

**Comment by marcjulian** [comment]
https://github.com/marcjulian/nest-prisma2 here is the example project. 

```bash
npm install
prisma2 lift up
npm run seed
npm run start
```

[localhost:3000/graphql](http://localhost:3000/graphql) and create the following mutation in the playground (email and password are inside of the auth resolver):

```graphql
mutation {
  login {
    token
  }
}
```

**Comment by Aircliff** [comment]
@marcjulian I've used photon in nestjs and havent run into any blocker issues yet, except the IDE (vscode) sometimes runs really really really slow after the types have been generated. Heres how i created my photon service:
```@Injectable()
export class PhotonService extends Photon {
  constructor() {
    super({
      autoConnect: true,
      debug: false,
    });
  }
}
```

and heres my schema.prisma connection info:

```
datasource pg {
  provider = "postgresql"
  // url      = env("POSTGRES_URL")
  url      = "postgresql://postgres:..."
}

generator photon {
  provider = "photonjs"
  output   = "../node_modules/@generated/photon"
}
```

**Comment by pantharshit00** [comment]
Closed by https://github.com/marcjulian/nest-prisma2/pull/1

You were terminating the connection on the finally block so photon was unable to make another call.

I have made it so that disconnection happens when the module is destroyed.

**Comment by marcjulian** [comment]
Thanks that works for me.
