### ISSUE TITLE
TypeError: Cannot read property 'content-encoding' of undefined

### ISSUE THREAD

**Issue by chrisui** [prisma/photonjs#159]
I'm getting the `TypeError: Cannot read property 'content-encoding' of undefined` error when running a simple seed script on generated photon client.

```
import Photon from './photon';

async function main() {
    const p = new Photon();
    await p.connect();

    await p.users.create({
        data: {
            email: 'chris@example.com',
            name: 'Chris',
            threads: {
                create: [
                    {name: "Example Thread"},
                ]
            }
        }
    });

    await p.disconnect();
}

main().catch(console.error);
```

```
ts-node ./seed/test.ts

TypeError: Cannot read property 'content-encoding' of undefined    at module.exports.757.module.exports (/usr/src/app/seed/photon/runtime/index.js:14534:50)
    at module.exports.474.module.exports (/usr/src/app/seed/photon/runtime/index.js:8976:31)
    at Object.<anonymous> (/usr/src/app/seed/photon/runtime/index.js:7267:5)
    at step (/usr/src/app/seed/photon/runtime/index.js:55:23)  
    at Object.next (/usr/src/app/seed/photon/runtime/index.js:36:53)
    at /usr/src/app/seed/photon/runtime/index.js:30:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/src/app/seed/photon/runtime/index.js:26:12)
    at ClientRequest.handleResponse (/usr/src/app/seed/photon/runtime/index.js:7198:40)
    at Object.onceWrapper (events.js:291:20)
(node:336) UnhandledPromiseRejectionWarning: RequestError: connect ECONNREFUSED 127.0.0.1:35603
(node:336) UnhandledPromiseRejectionWarning: Unhandled promise 
rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)      
(node:336) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:336) UnhandledPromiseRejectionWarning: RequestError: connect ECONNREFUSED 127.0.0.1:35603
```

```
datasource pg {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator photonjsSeed {
  provider = "photonjs"
  output   = "seed/photon"
}

model User {
  id          Int       @id
  createdAt   DateTime  @default(now())
  updatedAt   DateTime  @updatedAt
  email       String    @unique
  name        String?
  threads     Thread[]
}

model Thread {
  id          Int       @id
  createdAt   DateTime  @default(now())
  updatedAt   DateTime  @updatedAt
  name        String?
  people      User[]
}
```

**Comment by pantharshit00** [comment]
I am unable to reproduce this with prisma2@2.0.0-preview-3.2, binary version: acd6dd8dcf027b84a94af26b36ded779f1f56b1d

Can you please try again using the latest version? Also, if this is still reproducible please provide me with the details of your operating system.

**Comment by chrisui** [comment]
Have tried with latest version and am seeing the same error `prisma2@2.0.0-preview-3.2, binary version: acd6dd8dcf027b84a94af26b36ded779f1f56b1d`.

I'm running this from within a `node:12` docker container.

**Comment by pantharshit00** [comment]
Still no luck, maybe can you please make a git repo of the reproduction folder and share here?

**Comment by chrisui** [comment]
Having made a minimal issue repo with the client being generated into `node_modules/@generated/seed` and it working fine I tried changing my main repo to do the same (instead of building client into `seed/photon` and it suddenly worked. 

I've tried updating my issue repo to build into a random local directory but it still works fine. I'm a bit lost at this point but have at least resolved my original issue.

**Comment by pantharshit00** [comment]
So can we close this now?

**Comment by chrisui** [comment]
Yeah let's close for now and I'll come back if I find any more info to help figure out what was happening before.

**Comment by chrisui** [comment]
Thank you!
