### ISSUE TITLE
Support empty `where` statement for `findMany`

### ISSUE THREAD

**Issue by timsuchanek** [prisma/photonjs#165]
As of now, the query engine seems not to be able to parse an empty object:
```
Error: Error in Photon:
thread 'arbiter:1dc8d033-d2a7-4165-b64d-0a8361984814:actix-net-worker-2' panicked at 'object was empty', src/libcore/option.rs:1034:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::option::expect_failed
             at src/libcore/option.rs:1034
   9: core::builders::utils::extract_record_finder
  10: <core::builders::one::OneBuilder as core::builders::BuilderExt>::build
  11: core::builders::Builder::build
  12: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
  13: <&mut I as core::iter::traits::iterator::Iterator>::next
  14: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  15: core::builders::root::RootBuilder::build_query
  16: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
  17: <&mut I as core::iter::traits::iterator::Iterator>::next
  18: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  19: core::builders::root::RootBuilder::build
  20: <prisma::req_handlers::graphql::GraphQlRequestHandler as prisma::req_handlers::RequestHandler>::handle
  21: prisma::http_handler
  22: <F as actix_web::with::FnWith<T,R>>::call_with
  23: <actix_web::with::WithHandlerFut<T,S,R> as futures::future::Future>::poll
  24: actix_web::pipeline::PipelineState<S,H>::poll
  25: <actix_web::pipeline::Pipeline<S,H> as actix_web::server::handler::HttpHandlerTask>::poll_io
  26: actix_web::server::h1::Http1Dispatcher<T,H>::poll_handler
  27: actix_web::server::h1::Http1Dispatcher<T,H>::poll
  28: <actix_web::server::channel::HttpChannel<T,H> as futures::future::Future>::poll
  29: <actix_web::server::channel::HttpChannel<T,H> as futures::future::Future>::poll
  30: <actix_net::service::and_then::AndThenFuture<A,B> as futures::future::Future>::poll
  31: futures::future::chain::Chain<A,B,C>::poll
  32: futures::task_impl::std::set
  33: futures::task_impl::Spawn<T>::poll_future_notify
  34: tokio_current_thread::CurrentRunner::set_spawn
  35: tokio_current_thread::scheduler::Scheduler<U>::tick
  36: tokio_current_thread::Entered<P>::block_on
  37: std::thread::local::LocalKey<T>::with
  38: std::thread::local::LocalKey<T>::with
  39: std::thread::local::LocalKey<T>::with
  40: std::thread::local::LocalKey<T>::with
  41: tokio::runtime::current_thread::runtime::Runtime::block_on

    at PhotonFetcher.<anonymous> (/usr/app/node_modules/@generated/photon/index.js:37:23)
    at Generator.throw (<anonymous>)
    at rejected (/usr/app/node_modules/@generated/photon/index.js:5:65)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

**Comment by mavilein** [comment]
A fix is available in `alpha`.
