### ISSUE TITLE
Generating PhotonJS fails on Windows

### ISSUE THREAD

**Issue by MichalLytek** [prisma/photonjs#251]
The earlier versions were ok but prisma2 `alpha.231` fails with this error when I run `prisma2 generate`:

```
Error:
    Error: F:/#Projekty/#Github/typegraphql-prisma/examples/basic/node_modules/prisma2/build/photon-generator/index.js is not executable. Please run chmod +x node_modules/prisma2/build/photon-generator/index.js
        at new GeneratorProcess (F:/#Projekty/#Github/typegraphql-prisma/examples/basic/node_modules/prisma2/build/index.js:564634:19)
        at new Generator (F:/#Projekty/#Github/typegraphql-prisma/examples/basic/node_modules/prisma2/build/index.js:192475:33)
        at Object.<anonymous> (F:/#Projekty/#Github/typegraphql-prisma/examples/basic/node_modules/prisma2/build/index.js:682016:43)
        at Generator.next (<anonymous>)
        at F:/#Projekty/#Github/typegraphql-prisma/examples/basic/node_modules/prisma2/build/index.js:681965:71
        at new Promise (<anonymous>)
        at module.exports.__awaiter (F:/#Projekty/#Github/typegraphql-prisma/examples/basic/node_modules/prisma2/build/index.js:681961:12)
        at p_map_1.default.stopOnError (F:/#Projekty/#Github/typegraphql-prisma/examples/basic/node_modules/prisma2/build/index.js:682008:94)
        at F:/#Projekty/#Github/typegraphql-prisma/examples/basic/node_modules/prisma2/build/index.js:692242:21
```

The problem is that the `photon-generator/index.js` has shebang on top of the file (`#!/usr/bin/env node`) which doesn't work on Windows 😞

**Comment by pantharshit00** [comment]
Looks like this was already reported here: https://github.com/prisma/prisma2/issues/711

Since that issue has more information now, I am going to close this one as a duplicate.
