### ISSUE TITLE
Fail gracefully when model missing ID

### ISSUE THREAD

**Issue by jasonkuhrt** [prisma/photonjs#257]
The following model leads to DMMF that nexus-prisma will crash on:

```prisma
model User {
  id     String     @id @unique @default(cuid())
  posts  Post[]
  age    Int
  status UserStatus
}

model Post {
  id       String    @id @unique @default(cuid())
  author   User
  comments Comment[]
  rating   Float
}

model Comment {
  author  User
  post    Post
  content String
}

enum UserStatus {
  BANNED
  ACTIVE
}
```
```
/Users/jasonkuhrt/projects/prisma/nexus-prisma/examples/hello-world/node_modules/nexus-prisma/src/dmmf/DMMFClass.ts:130
      throw new Error(
            ^
Error: Could not find field field 'undefined' on type Query
    at OutputType.getField (/Users/jasonkuhrt/projects/prisma/nexus-prisma/examples/hello-world/node_modules/nexus-prisma/src/dmmf/DMMFClass.ts:130:13)
    at /Users/jasonkuhrt/projects/prisma/nexus-prisma/examples/hello-world/node_modules/nexus-prisma/src/mapping.ts:54:41
    at Array.map (<anonymous>)
    at Object.exports.getCrudMappedFields (/Users/jasonkuhrt/projects/prisma/nexus-prisma/examples/hello-world/node_modules/nexus-prisma/src/mapping.ts:50:64)
    at renderNexusPrismaInputs (/Users/jasonkuhrt/projects/prisma/nexus-prisma/examples/hello-world/node_modules/nexus-prisma/src/typegen.ts:114:25)
    at render (/Users/jasonkuhrt/projects/prisma/nexus-prisma/examples/hello-world/node_modules/nexus-prisma/src/typegen.ts:43:3)
    at doGenerate (/Users/jasonkuhrt/projects/prisma/nexus-prisma/examples/hello-world/node_modules/nexus-prisma/src/typegen.ts:26:25)
    at Object.generateSync (/Users/jasonkuhrt/projects/prisma/nexus-prisma/examples/hello-world/node_modules/nexus-prisma/src/typegen.ts:12:3)
    at new SchemaBuilder (/Users/jasonkuhrt/projects/prisma/nexus-prisma/examples/hello-world/node_modules/nexus-prisma/src/builder.ts:178:15)
    at Object.build [as nexusPrismaPlugin] (/Users/jasonkuhrt/projects/prisma/nexus-prisma/examples/hello-world/node_modules/nexus-prisma/src/builder.ts:98:19)
```
This change fixes it:

```diff
model Comment {
+ id      String @id @unique @default(cuid())
  author  User
  post    Post
  content String
}
```

Could Photon handle the bad model more gracefully?

**Comment by pantharshit00** [comment]
We would rather want to support the use case where the column doesn't have an ID.
https://github.com/prisma/prisma2/issues/175

I would close this as a duplicate but feel free to reopen if you want us to improve the error message while this is been implemented.
