### ISSUE TITLE
Can't have two sqlite datasources in the same schema

### ISSUE THREAD

**Issue by Errorname** [prisma/photonjs#265]
**Steps to reproduce:**

1. prisma2 init two-sqlite (choose sqlite)
2. Add a second datasource in the schema.prisma file
```
datasource db {
  provider = "sqlite"
  url      = "file:dev.db"
  enabled  = false
}

datasource db2 {
  provider = "sqlite"
  url      = "file:dev.db"
}
```
3. Run `prisma2 generate`

**Error:**
```
Error: Error: Could not parse datamodel, line 10: `datasource db2 {` is not parseable
    at /usr/local/lib/node_modules/prisma2/build/photon-generator/index.js:184074:23
    at Array.forEach (<anonymous>)
    at Object.extractSqliteSources (/usr/local/lib/node_modules/prisma2/build/photon-generator/index.js:184041:11)
    at /usr/local/lib/node_modules/prisma2/build/photon-generator/index.js:179795:63
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/prisma2/build/photon-generator/index.js:179761:71
    at new Promise (<anonymous>)
    at module.exports.__awaiter (/usr/local/lib/node_modules/prisma2/build/photon-generator/index.js:179757:12)
    at buildClient (/usr/local/lib/node_modules/prisma2/build/photon-generator/index.js:179786:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/prisma2/build/photon-generator/index.js:179864:47)
```

**Comment by timsuchanek** [comment]
Thanks a lot for reporting and the PR!
You can try your fix out with `npm i -g prisma2@alpha`.
