### ISSUE TITLE
Updating of non-existing record

### ISSUE THREAD

**Issue by vadim-shilov** [prisma/photonjs#297]
When I try to update a non-existing record Photon returns an error described below:
```
Error: 
Oops, an unknown error occured! This is on us, you did nothing wrong.
It occured in the `photon.()` invocation in /home/vadim/Projects/Temp/index.js:25:40



Reason: called `Option::unwrap()` on a `None` value in src/libcore/option.rs:378:21

Please create an issue in the photonjs repo with
your `schema.prisma` and the Photon method you tried to use 🙏:
https://github.com/prisma/photonjs/issues/new

    at PhotonFetcher.<anonymous> (/home/vadim/Projects/Temp/node_modules/@generated/photon/index.js:54:27)
    at Generator.throw (<anonymous>)
    at rejected (/home/vadim/Projects/Temp/node_modules/@generated/photon/index.js:6:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

OS: Ubuntu 18.04.3 LTS
Node.js version: 12.7.0
Prisma version: 2.0.0-preview016.2

**Comment by pantharshit00** [comment]
I can confirm this bug. Here is a reproduction: https://github.com/harshit-test-org/prisma-photonjs-297

**Comment by dpetrick** [comment]
This is fixed and will be in the next release.

**Comment by dpetrick** [comment]
This actually slipped into the Preview 17 release already. Please give it a spin and reopen the issue if the problem persists.

**Comment by janpio** [comment]
(Updated the milestone to reflect)
