### ISSUE TITLE
Errors at nested writes

### ISSUE THREAD

**Issue by vadim-shilov** [prisma/photonjs#302]
Hello!

Don't you think that throwing an error in the following cases is not worth it?

nested update of a non-existing record
```
Error: 
Invalid `photon.()` invocation in /home/vadim/Projects/Temp/index.js:11:36



Reason: AssertionError("Expected a valid parent ID to be present for nested update to-one case.")

    at PhotonFetcher.<anonymous> (/home/vadim/Projects/Temp/node_modules/@generated/photon/index.js:54:27)
    at Generator.throw (<anonymous>)
    at rejected (/home/vadim/Projects/Temp/node_modules/@generated/photon/index.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

disconnection/nested deletion of a non-existing record
```
Error: 
Invalid `photon.()` invocation in /home/vadim/Projects/Temp/index.js:11:36



Reason: RecordsNotConnected { relation_name: "PostToUser", parent_name: "User", child_name: "Post" }

    at PhotonFetcher.<anonymous> (/home/vadim/Projects/Temp/node_modules/@generated/photon/index.js:54:27)
    at Generator.throw (<anonymous>)
    at rejected (/home/vadim/Projects/Temp/node_modules/@generated/photon/index.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by pantharshit00** [comment]
I think this behaviour is expected. We just need to return better errors which will happen once error spec is implemented(https://github.com/prisma/specs/tree/master/errors)

**Comment by vadim-shilov** [comment]
Perhaps, in these cases, is no need to throw errors?
Maybe I'm wrong, but In my opinion, when rec is not connected the 'disconnect' action should complete successfully.
Regarding 'update' and 'delete' actions, I am of the same opinion.

**Comment by Jolg42** [comment]
I could reproduce 
```
  engine Engine Version query-engine 6a8054bb549e4cc23f157b0010cb2e95cb2637fb +0ms
  engine {
  engine   error: PrismaClientKnownRequestError: Query interpretation error. Error for binding '1': AssertionError("Expected a valid parent ID to be present for nested update to-one case.")
  engine       at NodeEngine.graphQLToJSError (/Users/j42/Dev/prisma/src/packages/client/src/__tests__/runtime-tests/blog-update/node_modules/@prisma/client/runtime/index.js:1:128787)
```

```
  prisma-client Prisma Client call: +94ms
  prisma-client prisma.user.update({
  prisma-client   where: {
  prisma-client     id: '576eddf9-2434-421f-9a86-58bede16fd95'
  prisma-client   },
  prisma-client   data: {
  prisma-client     name: null,
  prisma-client     profile: {
  prisma-client       update: {
  prisma-client         notrequired: null
  prisma-client       }
  prisma-client     }
  prisma-client   }
  prisma-client }) +1ms
  prisma-client Generated request: +0ms
  prisma-client mutation {
  prisma-client   updateOneUser(
  prisma-client     where: {
  prisma-client       id: "576eddf9-2434-421f-9a86-58bede16fd95"
  prisma-client     }
  prisma-client     data: {
  prisma-client       name: {
  prisma-client         set: null
  prisma-client       }
  prisma-client       profile: {
  prisma-client         update: {
  prisma-client           notrequired: {
  prisma-client             set: null
  prisma-client           }
  prisma-client         }
  prisma-client       }
  prisma-client     }
  prisma-client   ) {
  prisma-client     id
  prisma-client     email
  prisma-client     name
  prisma-client   }
  prisma-client }
```

schema
```
datasource db {
  provider = "sqlite"
  url      = "file:./dev.db"
}

generator client {
  provider = "prisma-client-js"
}

// / User model comment
model User {
  id    String  @default(uuid()) @id
  email String  @unique
  // / name comment
  name  String?
  posts Post[]
  profile Profile?
}

model Profile {
  id     String     @default(cuid()) @id
  bio    String?
  notrequired String?
  user   User    @relation(fields: [userId], references: [id])
  userId String     @unique
}

model Post {
  id        String   @default(cuid()) @id
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  published Boolean
  title     String
  content   String?
  optionnal String?
  authorId  String? @map("author")
  author    User?    @relation(fields: [authorId], references: [id])
}

```

**Comment by Jolg42** [comment]
Here what happened is that I had one User without a Profile and I was trying to update the Profile, which is not possible because it didn't exist (needs to be created first).
