### ISSUE TITLE
Photon facade with zeit now

### ISSUE THREAD

**Issue by divyenduz** [prisma/photonjs#323]
After the implementation of https://github.com/prisma/photonjs/issues/261

I tried deploying a package to now and I run into the following runtime errors: 

```
2019-12-09T12:45:29.934Z	undefined	ERROR	Error: @prisma/photon did not initialize yet. Please run "prisma2 generate" and try to import it again.
    at new Photon (/var/task/api/node_modules/@prisma/photon/index.js:3:11)
    at Object.<anonymous> (/var/task/api/index.js:7:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/var/task/___now_launcher.js:21:18)
Duration: 379.72 ms  Billed Duration: 400 ms  Memory Size: 1024 MB  Max Memory Used: 32 MB	
RequestId: 2f38c67f-5074-44bf-a977-4eda84a796c0 Error: Runtime exited with error: exit status 1
Runtime.ExitError
2019-12-09T12:46:30.877Z	undefined	ERROR	Error: @prisma/photon did not initialize yet. Please run "prisma2 generate" and try to import it again.
    at new Photon (/var/task/api/node_modules/@prisma/photon/index.js:3:11)
    at Object.<anonymous> (/var/task/api/index.js:7:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/var/task/___now_launcher.js:21:18)
Duration: 367.03 ms  Billed Duration: 400 ms  Memory Size: 1024 MB  Max Memory Used: 32 MB	
RequestId: 3e563d22-52da-49a9-88d3-2f2d2984148f Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

Reproduction repository: https://github.com/divyenduz/photonjs-323
Reproduction build: https://zeit.co/divyenduz/express-photon/cqgr17uaf (Divy has access)

**Comment by timsuchanek** [comment]
Thanks a lot for reporting 🙏
This issue is fixed in the latest alpha version of `prisma2`.
You can try it out with `npm i -g prisma2@alpha`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!
