### ISSUE TITLE
Unclear error with nextjs without migrations

### ISSUE THREAD

**Issue by steebchen** [prisma/photonjs#355]
The following error occurs when running photon against an empty database, i.e. if the user didn't run lift migrations.

```
❯ yarn build
yarn run v1.21.1
$ next build
Creating an optimized production build

Compiled successfully.

Automatically optimizing pages ..
Error occurred prerendering page "/" https://err.sh/zeit/next.js/prerender-error: Error: Error in Photon:
Error: undefined target="exit" timestamp="2019-12-16T17:29:33.341Z" fields={"message":"1"}
    at NodeEngine.engineReady (/private/tmp/np2/node_modules/@prisma/photon/runtime/index.js:3533:23)
    at PhotonFetcher.<anonymous> (/private/tmp/np2/node_modules/@prisma/photon/index.js:72:31)
    at Generator.throw (<anonymous>)
    at rejected (/private/tmp/np2/node_modules/@prisma/photon/index.js:6:65)
> Build error occurred
Error: Export encountered errors
    at _default (/private/tmp/np2/node_modules/next/dist/export/index.js:19:788)
    at process._tickCallback (internal/process/next_tick.js:68:7)
error Command failed with exit code 1.
```

After running `prisma2 lift save --create-db --name init && prisma2 lift up`, everything works fine, but the error message above should be improved.

A reproduction can be found at https://github.com/schickling/next-prisma2.

**Comment by steebchen** [comment]
related: https://github.com/prisma/photonjs/issues/305

**Comment by pantharshit00** [comment]
Closing in favour of https://github.com/prisma/photonjs/issues/357
