### ISSUE TITLE
Unintuitive Error when photon.users.findMany() without a configured datasource

### ISSUE THREAD

**Issue by matthewmueller** [prisma/photonjs#362]
Prisma schema without running lift or configuring a database

```prisma
generator photon {
  provider = "photonjs"
}

model User {
  id         Int      @id
  name       String
  posts      Post[]
  created_at DateTime @default(now())
  updated_at DateTime @updatedAt
}

model Post {
  id         Int      @id
  title      String
  author     User
  created_at DateTime @default(now())
  updated_at DateTime @updatedAt
}
```

Run `prisma generate`

```sh
prisma2 generate
```

Run this script with `ts-node`

```
import { Photon } from '@prisma/photon'
const photon = new Photon()

async function main() {
  return photon.users.findMany()
}

main()
  .then(console.log)
  .catch(console.error)
```

Results in:

```
Error:
Invalid `return photon.users.findMany()` invocation in /Users/m/Code/src/github.com/prisma/internal/jest-photon/simple.ts:5:23

  1 import { Photon } from '@prisma/photon'
  2 const photon = new Photon()
  3
  4 async function main() {
→ 5   return photon.users.findMany(

undefined target="exit" timestamp="2019-12-19T15:00:20.312Z" fields={"message":"1"}
    at PhotonFetcher.<anonymous> (/Users/m/Code/src/github.com/prisma/internal/jest-photon/node_modules/@prisma/photon/index.js:65:27)
    at Generator.throw (<anonymous>)
    at rejected (/Users/m/Code/src/github.com/prisma/internal/jest-photon/node_modules/@prisma/photon/index.js:6:65)
```

It should probably say something about not able to connect to the database

**Comment by divyenduz** [comment]
Related issue: https://github.com/prisma/photonjs/issues/357

**Comment by matthewmueller** [comment]
Ohhh 🔥 

Closing as a duplicate of #357
