### ISSUE TITLE
Can't perform reqeust, as the Engine has already been stopped

### ISSUE THREAD

**Issue by itzsaga** [prisma/photonjs#386]
Photon fails when trying to seed the DB.

Reproduction: https://github.com/itzsaga/prisma-93

```bash
seth@Seths-MacBook-Pro ~/dev/prisma-93                                                                                [12:24:16]
> $ yarn seed                                                                                                        [±master ✓]
yarn run v1.19.2
$ ts-node prisma/seed.ts
(node:59439) UnhandledPromiseRejectionWarning: Error:
Invalid `photon.()` invocation in /Users/seth/Dev/prisma-93/prisma/seed.ts:9:32



Can't perform reqeust, as the Engine has already been stopped
    at PhotonFetcher.<anonymous> (/Users/seth/Dev/prisma-93/node_modules/@prisma/photon/index.js:65:27)
    at Generator.throw (<anonymous>)
    at rejected (/Users/seth/Dev/prisma-93/node_modules/@prisma/photon/index.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:59439) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:59439) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by pantharshit00** [comment]
forEach loop doesn't actually halt when you call `await` in it. So your program completes execution and calls `photon.disconnect()` and then you get this error message.


What you need to do here is to either you `for await...of` loop or create a batch of Promises and await then using `Promise.all` like shown below:
```js
const seedBatch = durationUnit.map(d => {
    return photon.durationUnits.create({
      data: { duration_unit: d }
    });
  });

await Promise.all(seedBatch);

```

**Comment by itzsaga** [comment]
Thank you for the explanation @pantharshit00. I had a feeling it was something with `async/await` but in my searching diddn't find anything. Much appreciated.
