### ISSUE TITLE
Still imprecise "undefined target=exit" 

### ISSUE THREAD

**Issue by jean-noelp** [prisma/photonjs#414]
Hello,
Sorry, i updated my prisma versions to alpha as you proposed in [#357](https://github.com/prisma/photonjs/issues/357), and now i have this in my package.json:

```
"@prisma/client": "^2.0.0-alpha.539",
"prisma2": "^2.0.0-alpha.539",
```

Unfortunately, i still have the error msg as soon as i call ``photon.mytable...``:
```
Error: undefined target="exit" timestamp="2020-01-15T15:27:02.810Z" fields={"message":"1"}
    at NodeEngine.engineReady (/usr/src/app/node_modules/@prisma/photon/runtime/index.js:3545:23)
    at async /usr/src/app/node_modules/@prisma/photon/runtime/index.js:3468:21
```

How can i improve the precision of this message, at least ?

**Comment by jean-noelp** [comment]
In fact, the Docker image would not restart, and was keeping an old.
After a manual restart, the error disappear.
Great! Alpha was effectively the solution.
