### ISSUE TITLE
 prisma2 lift save - Error: Error in lift engine:

### ISSUE THREAD

**Issue by Kalcode** [prisma/photonjs#43]
On Windows 10 so it may be related to the enviroment.

Brand new clone, installed prisma2 via npm globally, followed the instructions

1. `npm install`
1. `npm install -g prisma2`
1. `prisma2 lift save --name 'init'`

And then i get the following error:

```shell
PS ~\Projects\photonjs\examples\typescript\graphql-apollo-server> prisma2 lift save --name 'init'
[migration-engine] error: Error: spawn C:\Users\kalan\AppData\Roaming\nvm\v12.4.0\node_modules\prisma2\migration-engine ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:9) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn ' +
    'C:\\Users\\kalan\\AppData\\Roaming\\nvm\\v12.4.0\\node_modules\\prisma2\\migration-engine',
  path: 'C:\\Users\\kalan\\AppData\\Roaming\\nvm\\v12.4.0\\node_modules\\prisma2\\migration-engine',
  spawnargs: []
}
Error: Error in lift engine: ****
```

**Comment by alireza-ahmadi** [comment]
I can confirm that this works on `macOS` without any issues so, as you said, it can be a Windows-only issue.

**Comment by JustinVoitel** [comment]
I get the same error on Windows (10.0.17134 Build 17134) and Linux (Ubuntu 19.04)

**Comment by matthewmueller** [comment]
Thanks for bringing this up! 

We're aware of this bug and we're tracking this issue here: https://github.com/prisma/prisma2-core/issues/4
